version: '3.4'

services:
  telegrambot:
    container_name: telegrambot
    image: ${DOCKER_REGISTRY-}telegrambot
    ports:
      - 32774:443
      - 32775:80
    volumes:
      - telegramBotLogs:/app/logs
      - telegramBotPhotos:/app/photos
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile
    environment:
      - AZURE_CLIENT_ID=9b5c4000-13d7-4c8e-aa9d-673894a2cb1b
      - AZURE_TENANT_ID=61a74b3d-1188-4c57-aed0-4171e8500298
      - AZURE_CLIENT_SECRET=wZA8Q~vyMHGS.U4m3-lKqj66oZLjX-uanJoBwbrv
  identity:
     container_name: identity
     image: ${DOCKER_REGISTRY-}identity
     ports:
      - 32776:443
      - 32777:80
     build:
      context: .
      dockerfile: Identity/Dockerfile
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - postgresData:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: boris.poloiko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadminData:/var/lib/pgadmin
volumes:
  telegramBotLogs:
    external: true
    name: TelegramBotLogs  
  telegramBotPhotos:
    external: true
    name: TelegramBotPhotos
  postgresData:
    external: true
    name: PostgresData
  pgadminData: